
-- 1. 아래와 같이 USER TEST 테이블을 만들고 데이터를 삽입하시오

DELETE USER_TEST;

CREATE TABLE USER_TEST (
	ID NUMBER,
	NAME VARCHAR2(3),
	RESERVEDATE VARCHAR2(10),
	ROOMNUM VARCHAR2(4)
);

ALTER TABLE USER_TEST MODIFY NAME VARCHAR2(30);

INSERT INTO USER_TEST VALUES(1, '홍길동', '2016-01-05', '2014');
INSERT INTO USER_TEST VALUES(2, '임꺽정', '2016-02-12', '918');
INSERT INTO USER_TEST VALUES(3, '장길산', '2016-01-16', '1208');
INSERT INTO USER_TEST VALUES(4, '홍길동', '2016-03-17', '504');
INSERT INTO USER_TEST VALUES(6, '김유신', NULL, NULL);

SELECT * FROM USER_TEST;

-- 2. USER_TEST테이블을 UPDATE/DELETE 구문을 사용하여 아래와 같이 수정하시오

DELETE FROM USER_TEST
WHERE ID = 6;

UPDATE USER_TEST 
SET ROOMNUM = '2002'
WHERE ID = 1;

UPDATE USER_TEST 
SET ROOMNUM = '2004'
WHERE ID = 4;

SELECT * FROM USER_TEST;

-- 3. USER_TEST 테이블을 UPDATE 구문을 사용하여 아래와 같이 수정하시오.

UPDATE USER_TEST 
SET ROOMNUM = '2002';

SELECT * FROM USER_TEST;


-- 4. EMPLOYEE5 테이블을 EMPLOYEE 테이블과 같이 생성하기

CREATE TABLE EMPLOYEE5 AS SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE5;

-- 5. EMPLOYEE5 테이블에서 고용일이 2000년대 이전인 사람의 월급을 100만원씩 인상해주자

UPDATE EMPLOYEE5
SET SALARY = SALARY + 1000000
WHERE SUBSTR(TO_CHAR(HIRE_DATE, 'YYYYMMDD'), 1, 4) <= 2000;

SELECT * FROM EMPLOYEE5
WHERE SUBSTR(TO_CHAR(HIRE_DATE, 'YYYYMMDD'), 1, 4) <= 2000;

-- 6. EMPLOYEE5 테이블에서 한국에 근무하는 직원의 BONUS를 0.5로 변경

SELECT * FROM EMPLOYEE5;

UPDATE EMPLOYEE5
SET BONUS = 0.5
WHERE EMP_NAME IN (SELECT EMP_NAME
		FROM EMPLOYEE5
		JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
		JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE)
		NATURAL JOIN (NATIONAL)
		WHERE NATIONAL_NAME = '한국');

SELECT EMP_NAME, BONUS
		FROM EMPLOYEE5
		JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
		JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE)
		NATURAL JOIN (NATIONAL)
		WHERE NATIONAL_NAME = '한국';
